name: Build Native AOT for macOS

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # برای اینکه بتوانی دستی با یک دکمه هم اجرا کنی

jobs:
  build-macos:
    runs-on: macos-latest # اجرای بیلد روی سرورهای واقعی مک اپل

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x' # یا 9.0.x و 8.0.x متناسب با نسخه دات‌نت شما

    - name: Publish Native AOT for macOS (Apple Silicon)
      run: |
        dotnet publish -c Release -r osx-arm64

    - name: Upload macOS Binary
      uses: actions/upload-artifact@v4
      with:
        name: HashCalculator-macOS-AppleSilicon
        path: "**/bin/Release/**/osx-arm64/publish/HashCalculator"